baseurl = "/"
languageCode = "en-us"
title = "Your Property Consultant"
theme = "bingo"

disableHugoGeneratorInject = true
enableEmoji = true
footnoteReturnLinkContents = "↩"
hasCJKLanguage = true
googleAnalytics = ""

[permalinks]
  post = "/posts/:slug/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Updates & Sharing"
    url = "/posts"
    weight = 20

  [[menu.main]]
    identifier = "new"
    name = "New Projects"
    url = "/projects"
    weight = 30 
    
  [[menu.main]]
    identifier = "map"
    name = "Map"
    url = "/map"
    weight = 50    
    
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 60    
    