baseurl = "https://yourproperty.sg/"
languageCode = "en-us"
title = "Your Property"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Zack Lim"
    description = "Buy, sell and rent property"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Updates & Sharing"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "New Projects"
    weight = 3
    
[[menu.main]]
    url = "/resale/"
    name = "Resale"
    weight = 4    
    
[[menu.main]]
    url = "/map/"
    name = "Map"
    weight = 5

[[menu.icon]]
    url = "/contact/"
    name = "envelope-o"
    weight = 1
