backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Blog"
    name: "post"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", required: false, widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}                
  - label: "Project"
    name: "project"
    folder: "content/project"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", required: false, widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}